name: Test Release

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
    uses: actions/checkout@v2

    - name: Set up Git
    run: |
      git config user.name "github-actions"
      git config user.email "github-actions@github.com"

    - name: Create random tag
    id: create_tag
    run: |
      TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
      echo "::set-output name=tag::$TAG_NAME"

    - name: Push tag to repository
    run: |
      git tag ${{ steps.create_tag.outputs.tag }}
      git push origin ${{ steps.create_tag.outputs.tag }}